version: '3.8'

services:
  web:
    build: .
    container_name: fastapi_app
    ports:
      - "8001:8001"
    depends_on:
      - db
    env_file:
      - .env.container

  db:
    image: postgres:13
    ports:
      - "5466:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data/
    env_file:
      - .env.container

# Локальная директория: ./db-data
# Директория в контейнере: /var/lib/postgresql/data/